#!/bin/bash

# If not run as root quit

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

# Update Apt repositories

apt-get update

# Upgrade to latest versions currently released for the default installation

apt-get upgrade -y

# Install SSH

apt-get install ssh -y


# Add itself to netbox via API call. This is a work in progress

#

